# Site settings
name: Thomas Tsagklas
email: tsagklas@mail.com
#canonical_url: https://edwinexemplar.com
keywords: "Network Engineer, Sales Engineer, Presales Engineer, SD-WAN, SDN, NFV, Routing, Swithcing"
skills: "Specialist in Traditional and Modern Network Technologies - London, UK"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/thomastsagklas/
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6a0dad
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: d3d3d3
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
